name: Sync Upstream Repository

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时自动同步一次
  workflow_dispatch:       # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 配置Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: 添加上游仓库并同步
        run: |
          git remote add upstream https://github.com/DSPBluePrints/FactoryBluePrints.git
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit
          git push origin main
      - name: 推送到 Gitee
        run: |
          echo "https://scarylb:${{ secrets.GITEE_TOKEN }}@gitee.com" > ~/.git-credentials
          git config --global credential.helper store
          git push https://gitee.com/scarylb/FactoryBluePrints.git main -f
